##################################
#     SERVER
##################################
server:
  port: 8080

##################################
#     SPRING CONFIG
##################################
spring:
  application:
    name: api-gateway

  ##################################
  #     API GATEWAY CONFIG
  ##################################
  cloud:
    gateway:
      routes:
        # Client Service
        - id: clients-service
          uri: lb://clients-service
          predicates:
            - Path=/api/clients/*

        # Medicine Service
        - id: medicine-service
          uri: lb://medicine-service
          predicates:
            - Path=/api/medicines/**

##################################
#     EUREKA DISCOVERY CONFIG
##################################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

##################################
#     ACTUATOR CONFIG
##################################
management:
  endpoints:
    web:
      exposure:
        include: health,info